apiVersion: v1
kind: ConfigMap
metadata:
  name: gointern-scheduler-logback-config
data:
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
        
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{trace_id:-},%X{span_id:-}] [%thread] %logger{0} - %msg%n</pattern>            </encoder>
        </appender>

        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/app/application.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                <fileNamePattern>/var/log/app/application.%d{yyyy-MM-dd}.log</fileNamePattern>
                <maxHistory>3</maxHistory>
                <totalSizeCap>1GB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{trace_id:-},%X{span_id:-}] [%thread] %logger{0} - %msg%n</pattern>            </encoder>
        </appender>
        
        <appender name="ERROR_STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <filter class="ch.qos.logback.classic.filter.LevelFilter">
                <level>ERROR</level>
                <onMatch>ACCEPT</onMatch>
                <onMismatch>DENY</onMismatch>
            </filter>
            <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
                <pattern>ðŸš¨ %d{yyyy-MM-dd HH:mm:ss} ERROR [%logger{0}] %msg%n%ex{3}</pattern>
            </encoder>
        </appender>
        
        <logger name="com.goyoai" level="INFO"/>
        
        <logger name="com.goyoai.service" level="DEBUG"/>
        <logger name="com.goyoai.controller" level="INFO"/>
        
        <logger name="org.apache" level="ERROR"/>
        <logger name="io.netty" level="ERROR"/>
        <logger name="reactor" level="ERROR"/>
        
        <root level="INFO">
            <appender-ref ref="STDOUT"/>
            <appender-ref ref="ERROR_STDOUT"/>
            <appender-ref ref="FILE"/>
        </root>
    </configuration>