apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-web-backoffice-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev-bo-api.go-intern.io`)
      priority: 12
      services:
        - name: goyoai-gointern-backoffice
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`dev-bo-api.go-intern.io`) && PathPrefix(`/grpc`)
      priority: 13
      services:
        - name: goyoai-gointern-backoffice
          namespace: goyoai-web
          port: 5000
          scheme: h2c

    - kind: Rule
      match: Host(`dev-bo.go-intern.io`)
      priority: 12
      services:
        - name: goyoai-gointern-bo-web
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`dev-bo.go-intern.io`) && PathPrefix(`/grpc`)
      priority: 13
      services:
        - name: goyoai-gointern-bo-web
          namespace: goyoai-web
          port: 5000
          scheme: h2c
  tls:
    secretName: goyoai-web-backoffice-tls