apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-internal-http
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gdgr.go-intern.io`)
      middlewares:
        - name: redirect-http-https
      services:
        - name: goyo-grafana
          namespace: lgtm
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-internal-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdgr.go-intern.io`)
      priority: 10
      services:
        - name: goyo-grafana
          namespace: lgtm
          port: 80
  tls: 
    secretName: goyoai-web-backoffice-tls