apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kyverno-internal-http
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gdkv.go-intern.io`)
      middlewares:
        - name: redirect-http-https
      services:
        - name: policy-reporter-ui
          namespace: kyverno
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kyverno-internal-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdkv.go-intern.io`)
      priority: 10
      services:
        - name: policy-reporter-ui
          namespace: kyverno
          port: 8080
    - kind: Rule
      match: Host(`gdkv.go-intern.io`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 11
      services:
        - namespace: authentik
          name: authentik-server
          port: 80
  tls: 
    secretName: goyoai-web-backoffice-tls