apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-internal-http
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gdtek.go-intern.io`)
      middlewares:
        - name: redirect-http-https
      services:
        - name: tekton-dashboard
          namespace: tekton-pipelines
          port: 9097
    - kind: Rule
      match: Host(`gdkphb.go-intern.io`)
      middlewares:
        - name: redirect-http-https
      services:
        - name: el-kustomize-patch-harbor-listener
          namespace: tekton-pipelines
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-internal-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdtek.go-intern.io`)
      priority: 10
      middlewares:
        - name: forwardauth
          namespace: traefik
      services:
        - name: tekton-dashboard
          namespace: tekton-pipelines
          port: 9097
    - kind: Rule
      match: Host(`gdtek.go-intern.io`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 11
      services:
        - namespace: authentik
          name: authentik-server
          port: 80
    - kind: Rule
      match: Host(`gdkphb.go-intern.io`)
      priority: 10  
      services:
        - name: el-kustomize-patch-harbor-listener
          namespace: tekton-pipelines
          port: 8080
  tls: 
    secretName: goyoai-web-backoffice-tls