apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-internal-http
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gdvt.go-intern.io`)
      middlewares:
        - name: redirect-http-https
      services:
        - name: goyo-vault-ui
          namespace: vault
          port: 8200
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-internal-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdvt.go-intern.io`)
      priority: 10
      services:
        - name: goyo-vault-ui
          namespace: vault
          port: 8200
  tls:
    secretName: goyoai-web-backoffice-tls