# Frontend 전용 안전한 PVC 구성
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.project_name }}-main
  namespace: tekton-pipelines
  labels:
    app: goyoai-gointern-web
    environment: main
    component: workspace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage_ClassName}}
  resources:
    requests:
      storage: {{ .Values.storage_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.project_name }}-pr
  namespace: tekton-pipelines
  labels:
    app: goyoai-gointern-web
    environment: pr
    component: workspace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage_ClassName}}
  resources:
    requests:
      storage: {{ .Values.storage_size }}