apiVersion: v1
kind: Service
metadata:
  name: uclick-aify-studio-web-feature-aify-studio
  labels:
    app.kubernetes.io/component: uclick-aify-studio-web-feature-aify-studio-generator
    app.kubernetes.io/instance: uclick-aify-studio-web-feature-aify-studio-generator
    app.kubernetes.io/part-of: uclick-aify-studio-web-feature-aify-studio-generator
spec:
  type: ClusterIP
  selector:
    app: uclick-aify-studio-web-feature-aify-studio-app
  ports:
  - port: 5000
    targetPort: 3000