apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.project_name }}
  namespace: tekton-pipelines
spec:
  serviceAccountName: {{ .Values.el_serviceAccountName }}
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            nodeSelector:
              {{ .Values.el_node_selector_key }}: {{ .Values.el_node_selector_value }}
            tolerations:
              - key:  {{ .Values.el_tolerations_key }}
                operator: {{ .Values.el_tolerations_operator }}
                value: {{ .Values.el_tolerations_value }}
                effect: {{ .Values.el_tolerations_effect }}
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
  triggers:
    - name: {{ .Values.project_name }}-push
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: |
                body.ref.split('/')[2] in [{{ range $index, $revision := .Values.gitRevisions }}{{ if $index }},{{ end }}'{{ $revision }}'{{ end }}]
            - name: "overlays"
              value:
                - key: sha
                  expression: "body.head_commit.id"
                - key: short_sha
                  expression: "body.head_commit.id.truncate(7)"
                - key: branch_name
                  expression: "body.ref.split('/')[2]"
                - key: deploy_env
                  expression: |
                    body.ref.split('/')[2] == 'prod-portal' ? 'production-portal' : 
                    body.ref.split('/')[2] == 'prod-system' ? 'production-system' : 'unknown'
                - key: module_name
                  expression: |
                    body.ref.split('/')[2] == 'prod-portal' ? 'goyoai-gointern-portal' : 'goyoai-gointern-system'
                - key: pvc_name
                  expression: |
                    body.ref.split('/')[2] == 'prod-portal' ? 'gointern-portal' : 'gointern-system'
                - key: dockerfile_name
                  expression: |
                    body.ref.split('/')[2] == 'prod-portal' ? 'dockerfile-portal-prod' : 'dockerfile-system-prod'
                
      bindings:
        - ref: {{ .Values.project_name }}
      template:
        ref: {{ .Values.project_name }}
    - name: {{ .Values.project_name }}-pr-open
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.action in ['opened', 'synchronize', 'reopened', 'labeled'] && body.pull_request.labels.exists(k, k.name=='deploy')"
            - name: "overlays"
              value:
                - key: sha
                  expression: "body.pull_request.head.sha"
                - key: short_sha
                  expression: "body.pull_request.head.sha.truncate(7)"
                - key: branch_name
                  expression: "body.pull_request.head.ref"
                - key: deploy_env
                  expression: "'pr-' + string(body.pull_request.number)"
                - key: module_name
                  expression: |
                    body.pull_request.head.ref.contains('portal') ? 'goyoai-gointern-portal' : 'goyoai-gointern-system'
                - key: pvc_name
                  expression: |
                    body.pull_request.head.ref.contains('portal') ? 'gointern-portal' : 'gointern-system'
                - key: dockerfile_name
                  expression: |
                    body.pull_request.head.ref.contains('portal') ? 'dockerfile-portal-prod' : 'dockerfile-system-prod'
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
      bindings:
        - ref: {{ .Values.project_name }}
      template:
        ref: {{ .Values.project_name }}
    - name: {{ .Values.project_name }}-pr-close
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.action == 'closed' || (body.action == 'unlabeled' && body.label.name == 'deploy')"
            - name: "overlays"
              value:
                - key: deploy_env
                  expression: "'pr-' + string(body.pull_request.number)"
        - ref:
              name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
      bindings:
        - ref: {{ .Values.project_name }}
      template:
        ref: {{ .Values.project_name }}-trigger-template