apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.project_name }}
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: {{ .Values.gitRevision }}  # Default to 'dev' branch
    - name: gitrepositoryurl
      description: The git repository URL
      default: {{ .Values.gitUrl }}
    - name: git-sha
    - name: git-short-sha
    - name: deploy-env
    - name: git-repo-name

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.project_name }}-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: {{ .Values.project_name }}
        params:
          - name: giturl
            value: "$(tt.params.gitrepositoryurl)"
          - name: container-registry-url
            value: "{{ .Values.container_registry_url }}"
          - name: container-registry-cache-url
            value: "{{ .Values.container_registry_cache_url }}"
          - name: manifest-file-name
            value: "{{ .Values.manifestFileName }}"
          - name: commit-message
            value: "Update $(tt.params.git-repo-name):$(tt.params.gitrevision) git hash: $(tt.params.git-short-sha) "
          - name: project-name
            value: "$(tt.params.git-repo-name)"
          - name: revision
            value: "$(tt.params.gitrevision)"
          - name: git-short-sha
            value: "$(tt.params.git-short-sha)"
        workspaces:
          - name: {{ .Values.project_name }}
            persistentVolumeClaim:
              claimName: {{ .Values.project_name }}
          - name: dockerconfig
            secret:
              secretName: {{ .Values.container_registry_secretName}}
        serviceAccountName: tekton-ci-token    
        podTemplate:         
          nodeSelector:
            {{ .Values.trigger_node_selector_key }}: "{{ .Values.trigger_node_selector_value }}"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: "{{ .Values.trigger_node_selector_key }}"
                    operator: {{ .Values.trigger_node_affinity_operator }}
                    values: 
                    - "{{ .Values.trigger_node_selector_value }}"
          tolerations:
          - key: "{{ .Values.trigger_tolerations_key }}"
            operator: "{{ .Values.trigger_tolerations_operator }}"
            value: "{{ .Values.trigger_tolerations_value }}"
            effect: "{{ .Values.trigger_tolerations_effect }}"