gitUrl: "https://github.com/GoyoAi-Service/goyoai-portal-scheduller"
gitRevision: "qa"
container_registry_secretName: "harborcred"
common_alpine_url: "gdharbor.goyoai.com/common/alpine:3.20.0"
common_alpine_git_url: "gdharbor.goyoai.com/common/git:2.45.2"
container_registry_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-back-portal-scheduler-dev"
container_registry_cache_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-back-portal-scheduller-cache-dev"
dockerfile: "dockerfile-qa"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
kustomize_git_branch: "goyoai-web-back-portal-scheduler"
manifestFileName: "goyoai-web-back-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "goyoai-web-back-portal-scheduler"
slack_webhook_url: "https://hooks.slack.com/services/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"