apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-https
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdauth.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 10
      services:
        - name: authentik-server
          port: 80
    - kind: Rule
      match: Host(`gdauth.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 11
      services:
        - name: authentik-server
          port: 80
          scheme: h2c
  tls: 
    secretName: authentik-tls
  # Include TLS configuration if Traefik is handling TLS2
