gitUrl: "https://github.com/kimseungwook/sukim-backend-system"
gitRevision: "dev-system"
el_serviceAccountName: "tekton-triggers-sa"
el_node_selector_key: "goyo-svc"
el_node_selector_value: "deploy"
el_tolerations_key: "goyo-svc"
el_tolerations_value: "deploy"
el_tolerations_operator: "Equal"
el_tolerations_effect: "NoSchedule"
trigger_node_selector_key: "goyo-svc"
trigger_node_selector_value: "deploy"
trigger_node_affinity_operator: "In"
trigger_tolerations_key: "goyo-svc"
trigger_tolerations_value: "deploy"
trigger_tolerations_operator: "Equal"
trigger_tolerations_effect: "NoSchedule"
dockerfile_name: "dockerfile-system-dev"
auth_token: "sukim-git-token"
container_registry_secretName: "harbor-registry-secret"
common_alpine_url: "gdhb.goyoai.com/common/alpine:3.20.3"
common_alpine_git_url: "gdhb.goyoai.com/common/git:2.45.2"
common_kaniko_url: "gdhb.goyoai.com/common/kaniko:1.23.2"
container_registry_url: "gdhb.goyoai.com/gointern"
container_registry_cache_url: "gdhb.goyoai.com/gointern-cache"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
back_kustomize_git_branch: "goyoai-backend-system"
portal_kustomize_git_branch: "goyoai-web-back-portal-v2"
back_kustomize_directory: "goyoai-backend-system/overlays/dev"
portal_kustomize_directory: "goyoai-web-back-portal-v2/overlays/dev"
back_deployment_name: "goyoai-backend-system"
portal_deployment_name: "goyoai-web-back-portal-v2"
manifestFileName: "goyoai-backend-system-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "gointern"
storage_ClassName: "oci-bv"
storage_size: "1Gi"
gradle_cache_pvc_name: "gointern-gradle-pvc"
slack_webhook_url: "https://hooks.slack.com/services/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"