apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-web-backoffice-http
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`dev-bo-api.go-intern.io`) && PathPrefix(`/`) 
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyoai-gointern-backoffice
          namespace: goyoai-web
          port: 5000

    - kind: Rule
      match: Host(`dev-bo.go-intern.io`) && PathPrefix(`/`) 
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyoai-gointern-bo-web
          namespace: goyoai-web
          port: 5000