apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goyoai-web-backend-relay
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 1Gi