auth:
  postgresPassword: "Goyoai123!@#"
  username: "goyoai"
  password: "Goyoai123!@#"
  database: "dev_goyoai_web"

primary:
  nodeSelector: 
    goyo-svc: deploy
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
  resourcesPreset: "nano"
  networkPolicy:
    enabled: false
  service:
    type: NodePort
    port: 30000
    targetPort: 5432


architecture: standalone