apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: hyper-report-backend-relay
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: develop_web  # Default to 'dev' branch
    - name: gitrepositoryurl
      description: The git repository URL
      default: "https://github.com/PROJECT-HYPER-REPORT/hyper-report-backend-relay"
    - name: git-sha
    - name: git-short-sha
    - name: deploy-env
    - name: git-repo-name

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hyper-report-backend-relay-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: hyper-report-backend-relay
        params:
          - name: giturl
            value: "$(tt.params.gitrepositoryurl)"
          - name: ocir-url
            value: "icn.ocir.io/cntwrbo3mm3p/hyper-report-qa-backend-relay"
          - name: ocir-cache-url
            value: "icn.ocir.io/cntwrbo3mm3p/hyper-report-qa-backend-relay-cache"
          - name: manifest-file-name
            value: "backend-manifest.yaml"
          - name: commit-message
            value: "Update $(tt.params.git-repo-name):$(tt.params.gitrevision) git hash: $(tt.params.git-short-sha) "
          - name: project-name
            value: "$(tt.params.git-repo-name)"
          - name: revision
            value: "$(tt.params.gitrevision)"
          - name: git-short-sha
            value: "$(tt.params.git-short-sha)"
        workspaces:
          - name: hyper-report-web
            persistentVolumeClaim:
              claimName: hyper-report-web
          - name: dockerconfig
            secret:
              secretName: ocirsecret
        serviceAccountName: tekton-ci-token    
        podTemplate:         
          nodeSelector:
            service: "tools"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: "service"
                    operator: In
                    values: 
                    - "tools"