apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
  labels:
    app.kubernetes.io/component: ecommerce-frontend
    app.kubernetes.io/instance: ecommerce-frontend
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  selector:
    app: ecommerce-frontend-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
