apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.project_name }}
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: develop_web  # Default to 'dev' branch
    - name: gitrepositoryurl
      description: The git repository URL
      default: "https://github.com/GoyoAi-Service/goyoai-web-back"
    - name: git-sha
    - name: git-short-sha
    - name: deploy-env
    - name: git-repo-name

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ .Values.project_name }}-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: {{ .Values.project_name }}
        params:
          - name: giturl
            value: "$(tt.params.gitrepositoryurl)"
          - name: container-registry-url
            value: "{{ .Values.container_registry_url }}"
          - name: container-registry-cache-url
            value: "{{ .Values.container_registry_cache_url }}"
          - name: manifest-file-name
            value: "frontend-manifest.yaml"
          - name: commit-message
            value: "Update $(tt.params.git-repo-name):$(tt.params.gitrevision) git hash: $(tt.params.git-short-sha) "
          - name: project-name
            value: "$(tt.params.git-repo-name)"
          - name: revision
            value: "$(tt.params.gitrevision)"
          - name: git-short-sha
            value: "$(tt.params.git-short-sha)"
        workspaces:
          - name: {{ .Values.project_name }}
            persistentVolumeClaim:
              claimName: {{ .Values.project_name }}
          - name: dockerconfig
            secret:
              secretName: {{ .Values.container_registry_secretName}}
        serviceAccountName: tekton-ci-token    
        podTemplate:         
          nodeSelector:
            goyo-svc: "deploy"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: "goyo-svc"
                    operator: In
                    values: 
                    - "deploy"
          tolerations:
          - key: "goyo-svc"
            operator: "Equal"
            value: "deploy"
            effect: "NoSchedule"