apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
spec:
  template:
    spec:
      containers:
        - name: ecommerce-frontend-container
          image: harbor.8ai.store/ecommerce/ecommerce-frontend:5d46730-20251230020914
