apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - ../../../base/ecommerce-frontend
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ecommerce-frontend
    path: deployment_patches.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ecommerce-frontend
    path: cpu_config.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ecommerce-frontend
    path: replica_config.yaml
