gitUrl: "https://github.com/GoyoAi-Service/goyoai-web-front-react-v2"
gitRevision: "prod-web"
dockerfile_name: "dockerfile-prod"
container_registry_secretName: "harborsecret"
common_alpine_url: "gphb.goyoai.com/common/alpine:3.20.3"
common_alpine_git_url: "gphb.goyoai.com/common/git:2.45.2"
container_registry_url: "gphb.goyoai.com/goyoai-web/goyoai-web-front-v2"
container_registry_cache_url: "gphb.goyoai.com/goyoai-web-cache/goyoai-web-front-v2-cache"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
kustomize_git_branch: "goyoai-web-front-v2"
kustomize_directory: "goyoai-web-front-v2/overlays/prod"
manifestFileName: "goyoai-web-front-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "goyoai-web-front-v2"
slack_webhook_url: "https://hooks.slack.com/services/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"