apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-aify-web
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-aify-web-container
          image: gphb.goyoai.com/goyoai-web/goyoai-aify-web:9711926-20251217070152
