apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
  labels:
    app.kubernetes.io/component: ecommerce-backend
    app.kubernetes.io/instance: ecommerce-backend
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  selector:
    app: ecommerce-backend-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
