apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-dashboard-ingressroute
  namespace: argocd
spec:
  entryPoints:
    - websecure  # This should be the entry point for HTTP traffic in Traefik
  routes:
    - match: PathPrefix(`/`) 
      kind: Rule
      services:
        - name: argocd-server
          namespace: argocd
          port: 80  # The port that the argocd-server service listens on for HTTP traffic
