apiVersion: v1
kind: Service
metadata:
  name: goyoai-gointern-backoffice
  labels:
    app.kubernetes.io/component: goyoai-gointern-backoffice-generator
    app.kubernetes.io/instance: goyoai-gointern-backoffice-generator
    app.kubernetes.io/part-of: goyoai-gointern-backoffice-generator
spec:
  type: ClusterIP
  selector:
    app: goyoai-gointern-backoffice-app
  ports:
  - port: 5000
    targetPort: 9195

---
apiVersion: v1
kind: Service
metadata:
  name: goyoai-gointern-backoffice-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "9292"
  labels:
    app: goyoai-gointern-backoffice-app
    app.kubernetes.io/component: goyoai-gointern-backoffice-generator
    app.kubernetes.io/instance: goyoai-gointern-backoffice-generator
    app.kubernetes.io/part-of: goyoai-gointern-backoffice-generator
spec:
  type: ClusterIP
  selector:
    app: goyoai-gointern-backoffice-app
  ports:
  - name: metrics 
    port: 9292
    targetPort: 9292
    protocol: TCP