gitUrl: "https://github.com/GoyoAi-Service/goyoai-web-back"
gitRevision: "qa-web-2nd"
container_registry_secretName: "harborcred"
common_alpine_url: "gdharbor.goyoai.com/common/alpine:3.20.0"
common_alpine_git_url: "gdharbor.goyoai.com/common/git:2.45.2"
container_registry_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-back-2nd-dev"
container_registry_cache_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-back-2nd-cache-dev"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
kustomize_git_branch: "goyoai-web-back"
kustomize_directory: "goyoai-web-back-2nd"
manifestFileName: "goyoai-web-back-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "goyoai-web-back-2nd"
slack_webhook_url: "https://hooks.slack.com/services/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"