apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goyoai-web-back-traefik-pdb
  namespace: goyoai-web
spec:
  minAvailable: 1
  selector:
    matchLabels:      
      app.kubernetes.io/instance: back-traefik-goyoai-web
      
      