gitUrl: "https://github.com/BBRICK-COMMON/RMS"
gitRevision: "prod"
serviceAccountName: "tekton-bbrick-token"
el_serviceAccountName: "tekton-triggers-sa"
el_node_selector_key: "goyo-svc"
el_node_selector_value: "deploy"
el_tolerations_key: "goyo-svc"
el_tolerations_value: "deploy"
el_tolerations_operator: "Equal"
el_tolerations_effect: "NoSchedule"
trigger_node_selector_key: "goyo-svc"
trigger_node_selector_value: "deploy"
trigger_node_affinity_operator: "In"
trigger_tolerations_key: "goyo-svc"
trigger_tolerations_value: "deploy"
trigger_tolerations_operator: "Equal"
trigger_tolerations_effect: "NoSchedule"
dockerfile_name: "dockerfile-prod"
container_registry_secretName: "harbor-registry-secret"
common_alpine_url: "gdhb.goyoai.com/common/alpine:3.20.3"
common_alpine_git_url: "gdhb.goyoai.com/common/git:2.45.2"
common_kaniko_url: "gdhb.goyoai.com/common/kaniko:1.23.2"
container_registry_url: "gdhb.goyoai.com/rms/bb_rms"
container_registry_cache_url: "gdhb.goyoai.com/rms-cache/bb_rms"
kustomize_git_url: "https://github.com/BBRICK-COMMON/rms-manifest"
kustomize_git_branch: "rms"
kustomize_directory: "rms/overlays/prod"
manifestFileName: "rms-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "rms"
storage_ClassName: "oci-bv"
storage_size: "1Gi"
slack_webhook_url: "https://hooks.slack.com/services/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"