global:
  clusterDomain: 'cluster.local'
  dnsService: 'kube-dns'
  dnsNamespace: 'kube-system'
  extraEnvFrom:
    - secretRef:
        name: objstore-secret

tempo:
  image:
    registry: docker.io
    repository: grafana/tempo
    pullPolicy: IfNotPresent
  extraArgs:
    - "-config.expand-env=true"

serviceAccount:
  create: true

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-bucket-sukim
      endpoint: cn7ipyag4bte.compat.objectstorage.ap-seoul-1.oraclecloud.com
      region: ap-seoul-1
      access_key: "${AWS_ACCESS_KEY_ID}"
      secret_key: "${AWS_SECRET_ACCESS_KEY}"
      insecure: false
      forcepathstyle: true

memcached:
  enabled: true
  replicas: 1
  nodeSelector:
    service: "monitoring"
memcachedExporter:
  enabled: true
  image:
    repository: "prom/memcached-exporter"
    tag: v0.15.4
    pullPolicy: IfNotPresent

ingester:
  replicas: 1
  nodeSelector:
    service: "monitoring"
  extraArgs:
    - "-config.expand-env=true"
  config:
    replication_factor: 1

distributor:
  replicas: 1
  nodeSelector:
    service: "monitoring"
  extraArgs:
    - "-config.expand-env=true"

querier:
  replicas: 1
  nodeSelector:
    service: "monitoring"
  extraArgs:
    - "-config.expand-env=true"

compactor:
  replicas: 1
  nodeSelector:
    service: "monitoring"
  extraArgs:
    - "-config.expand-env=true"

queryFrontend:
  replicas: 1
  nodeSelector:
    service: "monitoring"
  extraArgs:
    - "-config.expand-env=true"

metricsGenerator:
  enabled: true
  nodeSelector:
    service: "monitoring"
  extraArgs:
    - "-config.expand-env=true"
  config:
    storage:
      remote_write:
        - url: "http://prometheus-operated.prometheus.svc.cluster.local:9090/api/v1/write"