global:
  clusterDomain: 'cluster.local'
  dnsService: 'kube-dns'
  dnsNamespace: 'kube-system'

tempo:
  image:
    registry: docker.io
    repository: grafana/tempo
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  config:
    storage:
      remote_write:
        - url: "http://prometheus-operated.prometheus.svc.cluster.local:9090/api/v1/write"

traces:
  otlp:
    http:
      enabled: true  # Enable HTTP communication
    grpc:
      enabled: true  # Enable GRPC communication
metricsGenerator:
  enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-bucket-prd
      endpoint: cn7ipyag4bte.compat.objectstorage.ap-seoul-1.oraclecloud.com
      access_key: 4b8eb9627f942003c8b3d6b66fc6f6caefcb1b9a
      secret_key: "+hULmOEAxJI7sgAHZoGBow53K3EQsGbc52thwJKP7X8="
      insecure: false
memcached:
  nodeSelector:
    goyo-svc: "monitoring"
  tolerations: #[]
  - key: "goyo-svc"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"
    
ingester:
  replicas: 1
  nodeSelector:
    goyo-svc: "monitoring"
  tolerations: #[]
  - key: "goyo-svc"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"
  config:
    replication_factor: 1

distributor:
  replicas: 1
  nodeSelector:
    goyo-svc: "monitoring"
  tolerations: #[]
  - key: "goyo-svc"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"
  # extraArgs:
  #   "distributor.log-received-traces": true


querier:
  replicas: 1
  nodeSelector:
    goyo-svc: "monitoring"
  tolerations: #[]
  - key: "goyo-svc"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

compactor:
  replicas: 1
  nodeSelector:
    goyo-svc: "monitoring"
  tolerations: #[]
  - key: "goyo-svc"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

queryFrontend:
  replicas: 1
  nodeSelector:
    goyo-svc: "monitoring"
  tolerations: #[]
  - key: "goyo-svc"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

# gateway:
#   enabled: true
#   nodeSelector:
#     service: "monitoring"