apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.project_name}}
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 1Gi