apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: otlp-http
  namespace: otlp
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gdotlp.goyoai.com`) && PathPrefix(`/`) 
      # match: PathPrefix(`/`) 
      priority: 10
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyo-opentelemetry-collector
          port: 4318
