apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  annotations:
    kubernetes.io/ingress.class: noco-traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: noco.bbrick.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nocodb
                port:
                  number: 8080