apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nocodb-tls
  namespace: nocodb
spec:
  secretName: nocodb-tls
  issuerRef:
    name: nocodb-prod 
    kind: ClusterIssuer
  dnsNames:
    - noco.bbrick.com