apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-https
  namespace: nocodb
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gduk.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 10
      services:
        - namespace: uptime-kuma
          name: goyo-uptime-kuma
          port: 3001
    - kind: Rule
      match: Host(`gduk.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 11
      services:
        - namespace: uptime-kuma
          name: goyo-uptime-kuma
          port: 3001
          scheme: h2c
  tls:
    secretName: uptime-kuma-tls
  # Include TLS configuration if Traefik is handling TLS2
