apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nocodb-http
  namespace: nocodb
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gdno.goyoai.com`) && PathPrefix(`/`) 
      # match: PathPrefix(`/`) 
      priority: 10
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyo-nocodb
          port: 8080

    - kind: Rule
      match: Host(`gduk.goyoai.com`) && PathPrefix(`/`) 
      # match: PathPrefix(`/`) 
      priority: 11
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          namespace: uptime-kuma
          name: goyo-uptime-kuma
          port: 3001
