apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nocodb-https
  namespace: nocodb
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdno.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 10
      services:
        - name: goyo-nocodb
          port: 8080
    - kind: Rule
      match: Host(`gdno.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 11
      services:
        - name: goyo-nocodb
          port: 8080
          scheme: h2c
  tls:
    secretName: nocodb-tls
  # Include TLS configuration if Traefik is handling TLS2
