apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-https
  namespace: lgtm
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdgr.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 10
      services:
        - name: goyo-grafana
          port: 80
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`gdgr.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 11
      services:
        - name: goyo-grafana
          port: 80
          scheme: h2c
      # middlewares:
      #   - name: striptransferencoding
  tls:
    secretName: grafana-tls
  # Include TLS configuration if Traefik is handling TLS2
