gitUrl: "https://github.com/GoyoAi-Service/goyoai-web-front"
gitRevision: "develop_web"
container_registry_secretName: "harborcred"
common_alpine_url: "gdharbor.goyoai.com/common/alpine:3.19.1"
common_alpine_git_url: "gdharbor.goyoai.com/common/git:2.43.0"
container_registry_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-front-dev"
container_registry_cache_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-front-cache-dev"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
kustomize_git_branch: "goyoai-web-front"
manifestFileName: "goyoai-web-front-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "goyoai-web-front"
slack_webhook_url: "https://hooks.slack.com/services/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"