apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdargo.goyoai.com`)
      priority: 10
      services:
        - name: goyo-argocd-server
          namespace: argocd
          port: 80
    - kind: Rule
      match: Host(`gdargo.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-argocd-server
          namespace: argocd
          port: 80
          scheme: h2c
  tls:
    secretName: goyoai-webs-tls
