apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gointern-file-browser-https
  namespace: goyoai-web
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`gfb.goyoai.com`) && PathPrefix(`/`)
      middlewares:
        - name: redirect-http-https
      services:
        - namespace: goyoai-web
          name: goyoai-file-browser-service
          port: 80
    - kind: Rule
      match: Host(`gfb.goyoai.com`)
      priority: 10
      middlewares:
        - name: forwardauth
          namespace: goyoai-web
      services:
        - namespace: goyoai-web
          name: goyoai-file-browser-service
          port: 80
    - kind: Rule
      match: Host(`gfb.goyoai.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 11
      services:
        - namespace: goyoai-web
          name: goyoai-file-browser-service
          port: 80
    - kind: Rule
      match: Host(`gfb.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 12
      services:
        - namespace: goyoai-web
          name: goyoai-file-browser-service
          port: 80
          scheme: h2c    
  tls:
    secretName: goyoai-webs-tls