apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-web-apps-http
  namespace: goyoai-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`gointern-api.goyoai.com`) && PathPrefix(`/`)
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: dev-goyoai-backend-system
          port: 5000