apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-langfuse-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdlf.goyoai.com`)
      services:
        - name: goyo-langfuse
          namespace: goyoai-web
          port: 3000
  tls: 
    secretName: langfuse-tls
