apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: locust-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`locust.goyoai.com`)
      priority: 10
      middlewares:
        - name: forwardauth
          namespace: traefik
      services:
        - namespace: locust
          name: goyo-locust
          port: 8089
    - kind: Rule
      match: Host(`locust.goyoai.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 15      
      services:
        - namespace: authentik
          name: authentik-server
          port: 80
    - kind: Rule
      match: Host(`locust.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 20
      services:
        - name: goyo-locust
          namespace: locust
          port: 8089
          scheme: h2c
  tls:
    secretName: goyoai-webs-tls