apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mimir-gateway-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdmi.goyoai.com`)
      priority: 10
      services:
        - name: goyo-mimir-distributed-gateway
          namespace: lgtm
          port: 80
    - kind: Rule
      match: Host(`gdmi.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-mimir-distributed-gateway
          namespace: lgtm
          port: 80
          scheme: h2c
  tls: 
    secretName: goyo-mimir-gateway-tls