apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nocodb-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdno.goyoai.com`)
      priority: 10
      services:
        - name: goyo-nocodb
          namespace: nocodb
          port: 8080
    - kind: Rule
      match: Host(`gdno.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-nocodb
          namespace: nocodb
          port: 8080
          scheme: h2c
  tls:
    secretName: goyoai-webs-tls