apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdpa.goyoai.com`)
      priority: 10
      services:
        - name: goyo-pgadmin4
          namespace: postgresql
          port: 80
    - kind: Rule
      match: Host(`gdpa.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-pgadmin4
          namespace: postgresql
          port: 80
          scheme: h2c
  tls:
    secretName: goyo-pgadmin-tls
