apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdpro.goyoai.com`)
      priority: 10
      services:
        - name: prometheus-operated
          namespace: prometheus
          port: 9090
    - kind: Rule
      match: Host(`gdpro.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: prometheus-operated
          namespace: prometheus
          port: 9090
          scheme: h2c
  tls:
    secretName: goyo-prometheus-tls
