apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdrc.goyoai.com`)
      priority: 10
      services:
        - name: goyo-rancher
          namespace: rancher
          port: 80
    - kind: Rule
      match: Host(`gdrc.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-rancher
          namespace: rancher
          port: 80
          scheme: h2c
  tls:
    secretName: goyoai-webs-tls
