apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redis-commander-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdrg.goyoai.com`)
      priority: 10
      middlewares:
        - name: forwardauth
          namespace: traefik
      services:
        - namespace: redis
          name: redis-commander
          port: 80
    - kind: Rule
      match: Host(`gdrg.goyoai.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 11
      services:
        - namespace: authentik
          name: authentik-server
          port: 80

  tls:
    secretName: goyoai-webs-tls