apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sentry-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdstr.goyoai.com`)
      priority: 10
      services:
        - name: goyo-sentry-nginx
          namespace: sentry
          port: 80
    - kind: Rule
      match: Host(`gdstr.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-sentry-nginx
          namespace: sentry
          port: 80
          scheme: h2c
  tls: 
    secretName: goyo-sentry-tls