apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: uptime-kuma-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gduk.goyoai.com`)
      priority: 10
      middlewares:
        - name: forwardauth
          namespace: traefik
      services:
        - namespace: uptime-kuma
          name: goyo-uptime-kuma
          port: 3001
    - kind: Rule
      match: Host(`gduk.goyoai.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 11
      services:
        - namespace: authentik
          name: authentik-server
          port: 80
    - kind: Rule
      match: Host(`gduk.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 12
      services:
        - namespace: uptime-kuma
          name: goyo-uptime-kuma
          port: 3001
          scheme: h2c
    
  tls:
    secretName: goyoai-webs-tls