apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-https
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdvt.goyoai.com`)
      priority: 10
      services:
        - name: goyo-vault
          namespace: vault
          port: 8200
    - kind: Rule
      match: Host(`gdvt.goyoai.com`) && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: goyo-vault
          namespace: vault
          port: 8200
          scheme: h2c
  tls:
    secretName: goyoai-webs-tls
