apiVersion: v1
kind: Service
metadata:
  name: goyoai-gointern-web-feature-gointern-i18next
  labels:
    app.kubernetes.io/component: goyoai-gointern-web-feature-gointern-i18next-generator
    app.kubernetes.io/instance: goyoai-gointern-web-feature-gointern-i18next-generator
    app.kubernetes.io/part-of: goyoai-gointern-web-feature-gointern-i18next-generator
spec:
  type: ClusterIP
  selector:
    app: goyoai-gointern-web-feature-gointern-i18next-app
  ports:
  - port: 5000
    targetPort: 3000