apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-scheduler
spec:
  template:
    spec:
      containers:
        - name: goyoai-gointern-scheduler-container
          resources:
            requests:
              cpu: "2000m"
              memory: "5Gi"
            limits:
              cpu: "2000m"
              memory: "5Gi"
