# Ecommerce Backend 환경변수 ConfigMap
# TODO: 민감한 정보는 추후 Vault로 이전
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-backend-env
data:
  # App Configuration
  ENVIRONMENT: "production"
  HTTP_PORT: "8080"
  AUTH_SECRET: "VdGfi7o+zQV4YbYyyfpFeR2iCegyIFe14taY+JjlyZk="

  # Database Configuration
  DATABASE_URI: "postgres://ecommerce_user:L54MBfyZKoO5GhxcgpvXWOPl7bSqMWfaTdsq9cvVgCo=@ecommerce-pg-rw.cloudnative-pg.svc.cluster.local:5432/ecommerce_clean"

  # Redis Configuration
  REDIS_URI: "sukim-web-redis-master.redis.svc.cluster.local:6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"

  # MinIO Configuration
  MINIO_ENDPOINT: "minio.minio.svc.cluster.local:9000"
  MINIO_ACCESSKEY: "admin"
  MINIO_SECRETKEY: "P@ssw0rd11!!1234"
  MINIO_BUCKET: "ecommerce"
  MINIO_BASEURL: "https://minio-api.8ai.store"
  MINIO_USESSL: "false"

  # Mail Configuration
  MAIL_PORT: "587"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_USER: ""
  MAIL_PASSWORD: ""
  MAIL_FROM: ""
