apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-backend-promtail-config
  namespace: ecommerce
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: info
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki-gateway.monitoring.svc.cluster.local:80/loki/api/v1/push
        timeout: 10s
        backoff_config:
          min_period: 100ms
          max_period: 10s
          max_retries: 10
    
    scrape_configs:
      - job_name: ecommerce-backend
        static_configs:
          - targets:
              - localhost
            labels:
              job: ecommerce-backend
              namespace: ecommerce
              app: ecommerce-backend-app
              environment: dev
              node_type: virtual
              service_name: ecommerce-backend-app
              __path__: /var/log/app/*.log
