apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  template:
    spec:
      serviceAccountName: ecommerce-vault-sa
      containers:
        - name: ecommerce-backend-container
          image: harbor.8ai.store/ecommerce/ecommerce-backend:e92e2d4-20251230144830
