apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-aify-system
spec:
  template:
    spec:
      containers:
        - name: goyoai-aify-system-container
          resources:
            requests:
              cpu: "2000m"
              memory: "5Gi"
            limits:
              cpu: "2000m"
              memory: "5Gi"
