# values.yaml
gitUrl: "https://github.com/GoyoAi-Service/goyoai-backend-system"
gitRevisions: ["sukim-test"] # ⬅️ 단일 브랜치만 남김

# EventListener 설정
el_serviceAccountName: "tekton-triggers-sa"
el_node_selector_key: "goyo-svc"
el_node_selector_value: "deploy"
el_tolerations_key: "goyo-svc"
el_tolerations_value: "deploy"
el_tolerations_operator: "Equal"
el_tolerations_effect: "NoSchedule"

# 일반 Task용 노드 설정 (generate-timestamp, clone, manifest-push)
trigger_node_selector_key: "goyo-svc"
trigger_node_selector_value: "deploy"
trigger_tolerations_key: "goyo-svc"
trigger_tolerations_value: "deploy"
trigger_tolerations_operator: "Equal"
trigger_tolerations_effect: "NoSchedule"

# Container images
container_registry_secretName: "harbor-registry-secret"
common_alpine_url: "gdhb.goyoai.com/common/alpine:3.20.3"
common_alpine_git_url: "gdhb.goyoai.com/common/git:2.45.2"
container_registry_url: "gdhb.goyoai.com/goyoai-web"
container_registry_cache_url: "gdhb.goyoai.com/goyoai-web-cache"

# Kustomize 설정 (System 용만 남김)
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
back_kustomize_git_branch: "goyoai-backend-system"
back_kustomize_directory: "goyoai-backend-system/overlays/dev"
back_deployment_name: "goyoai-backend-system"
manifestFileName: "goyoai-backend-system-manifest.yaml"
commitMessage: "Update Kubernetes manifest"

# 프로젝트 설정
project_name: "goyoai-backend-system"

# Task 이름 (System 용만 남김)
system_build_task_name: "goyoai-gointern-system-image-build"

# Slack
slack_webhook_url: "https://hooks.slack.com/services/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"
slack_message: "Build completed"