apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-bo-web
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-gointern-bo-web-container
          image: gphb.goyoai.com/goyoai-web/goyoai-gointern-bo-web:9711926-20251217070150
