gitUrl: "https://github.com/GoyoAi-Service/goyoai-web-page"
gitRevision: "develop"
container_registry_secretName: "harborcred"
common_alpine_url: "gdharbor.goyoai.com/common/alpine:3.20.0"
common_alpine_git_url: "gdharbor.goyoai.com/common/git:2.45.2"
dockerfile_name: "dockerfile"
container_registry_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-page"
container_registry_cache_url: "gdharbor.goyoai.com/goyoai-web/goyoai-web-page-cache"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
kustomize_git_branch: "goyoai-web-page"
manifestFileName: "goyoai-web-page.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "goyoai-web-page"
slack_webhook_url: "https://hooks.slack.com/services/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"