apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-portal
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-gointern-portal-container
          image: gphb.goyoai.com/goyoai-web/goyoai-gointern-portal:279c17b-20251218084212
