apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - goyoai-aify-portal-app.yaml
  - goyoai-aify-scheduler-app.yaml
  - goyoai-aify-system-app.yaml
  - goyoai-gointern-backoffice-app.yaml
  - goyoai-gointern-message-app.yaml
  - goyoai-gointern-portal-app.yaml
  - goyoai-gointern-scheduler-app.yaml
  - goyoai-gointern-system-app.yaml
