apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-system
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-gointern-system-container
          image: gphb.goyoai.com/goyoai-web/goyoai-gointern-system:9342963-20251224100426
