apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: tekton-pipelines
spec:
  profile: all
  config:
    nodeSelector:
      service: tools
    priorityClassName: system-node-critical