apiVersion: v1
kind: Service
metadata:
  name: goyoai-cosmos-web
  labels:
    app.kubernetes.io/component: goyoai-cosmos-web-generator
    app.kubernetes.io/instance: goyoai-cosmos-web-generator
    app.kubernetes.io/part-of: goyoai-cosmos-web-generator
spec:
  type: ClusterIP
  selector:
    app: goyoai-cosmos-web-app
  ports:
  - port: 5000
    targetPort: 3000