apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: authentik-headers
    namespace: traefik
spec:
    headers:
        customRequestHeaders:
            X-Forwarded-Host: "gauthentik.goyoai.com"
            X-Forwarded-Proto: "https"
            X-Real-IP: "%%{remote_addr}%%"