apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-trigger-back-2nd-https
  namespace: tekton-pipelines
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdwback2nddev.goyoai.com`)
      priority: 14
      services:
        - name: el-goyoai-web-back-2nd
          port: 8080
  tls: 
    secretName: tekton-trigger-back-2nd-tls
