apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-trigger-frontend-https
  namespace: tekton-pipelines
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdwfrontdev.goyoai.com`)
      priority: 13
      services:
        - name: el-goyoai-web-front
          port: 8080
  tls: 
    secretName: tekton-trigger-frontend-web-tls
