apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-dashboard-https
  namespace: tekton-pipelines
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdtek.goyoai.com`)
      priority: 10
      services:
        - name: tekton-dashboard
          port: 9097
    - kind: Rule
      match: Host(`gdtek.goyoai.com`)  && PathPrefix(`/grpc`)
      priority: 11
      services:
        - name: tekton-dashboard
          port: 9097
          scheme: h2c
  tls: 
    secretName: tekton-dashboard-tls
