apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-trigger-backend-https
  namespace: tekton-pipelines
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gdwbackdev.goyoai.com`)
      priority: 14
      services:
        - name: el-goyoai-web-back
          port: 8080
  tls: 
    secretName: tekton-trigger-backend-relay-tls
