apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-ai-server
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-ai-server-container
          image: gphb.goyoai.com/goyoai-web/goyoai-ai-server:dc2bf11-20251123102029
