apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: {{ .Values.project_name }}-gitops-update
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: {{ .Values.serviceAccountName }}
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            nodeSelector:
              service: "tools"
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
  triggers:
    - name: {{ .Values.project_name }}-http-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "has(body.app_name) && has(body.image_tag)"
      bindings:
        - ref: {{ .Values.project_name }}-gitops-binding
      template:
        ref: {{ .Values.project_name }}-gitops-template