apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: {{ .Values.project_name }}-gitops-binding
  namespace: {{ .Values.namespace }}
spec:
  params:
    - name: app-name
      value: $(body.app_name)
    - name: image-tag
      value: $(body.image_tag)
    - name: registry
      value: $(body.registry)
    - name: namespace-env
      value: $(body.namespace)