apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ingress-noco
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: argocd
    apiGroup: ingress.oraclecloud.com
    kind: ingressclassparameters
    name: argocd-ingress-params