apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocodb-ingress
  namespace: nocodb
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: ingress-nginx-lb
  tls:
  - hosts:
    - noco.bbrick.com
    secretName: ingress-nocodb-tls   
  rules:
    - host: "noco.bbrick.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nocodb-traefik
                port:
                  number: 80
