apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-frontend-web-http
  namespace: goyoai-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`dev2.goyoai.com`)
      priority: 10
      services:
        - name: goyoai-gointern-web
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`dev3.goyoai.com`)
      priority: 10
      services:
        - name: goyoai-gointern-web
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`dev-aify.goyoai.com`)
      priority: 10
      services:
        - name: goyoai-aify-web
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`dev.goyoai.com`)
      priority: 10
      services:
        - name: goyoai-gointern-web-feature-gointern-i18next
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`dev-cosmos.goyoai.com`)
      priority: 10
      services:
        - name: goyoai-cosmos-web
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`studio.aify.ai`)
      priority: 10
      services:
        - name: uclick-aify-studio-web-feature-aify-studio
          namespace: goyoai-web
          port: 5000
    - kind: Rule
      match: Host(`studio.goyoai.com`)
      priority: 10
      services:
        - name: uclick-aify-studio-web-feature-aify-studio
          namespace: goyoai-web
          port: 5000