apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gointern-redis-tcp
  namespace: traefik
spec:
  entryPoints:
    - gointern-redis-tcp # Traefik에 gointern-redis-tcp entryPoint가 정의되어 있어야 함
  routes:
    - match: "HostSNI(`*`)" # TCP 라우팅은 SNI 매칭 사용
      # kind: Rule
      services:
        - name: goyoai-backend-system-redis-master
          namespace: redis
          port: 6379
  # tls:  # TLS 설정 추가
  #   passthrough: true  # TLS 연결을 그대로 통과