apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql-tcp
  namespace: traefik
spec:
  entryPoints:
    - mysql # Traefik에 mysql entryPoint가 정의되어 있어야 함
  routes:
    - match: "HostSNI(`*`)" # TCP 라우팅은 SNI 매칭 사용
      # kind: Rule
      services:
        - name: rms-mysql
          namespace: rms
          port: 3306
  # tls:  # TLS 설정 추가
  #   passthrough: true  # TLS 연결을 그대로 통과