apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noco-ingress
  namespace: nocodb
spec:
  tls:
  - hosts:
      - noco.bbrick.com
    secretName: noco-tls-secret  
  ingressClassName: native-ingress-noco
  rules:
  - host: "noco.bbrick.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: noco-traefik
            port:
              number: 80