apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-aify-portal
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-aify-portal-container
          image: gphb.goyoai.com/goyoai-web/goyoai-aify-portal:82b14e7-20251217070552
