apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: aify-https
  namespace: aify
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`aify.goyoai.com`) && PathPrefix(`/`)
      # match: PathPrefix(`/`) 
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyoai-aify-web
          port: 5000
    - kind: Rule
      match: Host(`aify.goyoai.com`)
      # match: PathPrefix(`/`)
      priority: 14
      services:
        - name: goyoai-aify-web
          port: 5000
    - kind: Rule
      match: Host(`aify.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-aify-web
          port: 5000
          scheme: h2c

    - kind: Rule
      match: Host(`aify-api.goyoai.com`) && PathPrefix(`/`)
      # match: PathPrefix(`/`) 
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyoai-aify-system
          port: 5000
    - kind: Rule
      match: Host(`aify-api.goyoai.com`)
      # match: PathPrefix(`/`)
      priority: 14
      services:
        - name: goyoai-aify-system
          port: 5000
    - kind: Rule
      match: Host(`aify-api.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-aify-system
          port: 5000
          scheme: h2c
          
    - kind: Rule
      match: Host(`aify-api-portal.goyoai.com`) && PathPrefix(`/`)
      # match: PathPrefix(`/`) 
      middlewares:
        - name: redirect-http-https
      services:
        - kind: Service
          name: goyoai-aify-portal
          port: 5000
    - kind: Rule
      match: Host(`aify-api-portal.goyoai.com`)
      # match: PathPrefix(`/`)
      priority: 14
      services:
        - name: goyoai-aify-portal
          port: 5000
    - kind: Rule
      match: Host(`aify-api-portal.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-aify-portal
          port: 5000
          scheme: h2c
  tls:
    secretName: aify-tls
  # Include TLS configuration if Traefik is handling TLS2
