apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-web-back-https
  namespace: goyoai-web
spec:
  entryPoints:
    - websecure
  routes:
    # - kind: Rule
    #   match: Host(`go-intern2-api.goyoai.com`)
    #   # match: PathPrefix(`/`) 
    #   priority: 14
    #   services:
    #     - name: goyoai-web-back
    #       port: 5000
    #   # middlewares:
    #   #   - name: striptransferencoding
    # - kind: Rule
    #   match: Host(`go-intern2-api.goyoai.com`) && PathPrefix(`/grpc`)
    #   # match: PathPrefix(`/`) 
    #   priority: 15
    #   services:
    #     - name: goyoai-web-back
    #       port: 5000
    #       scheme: h2c
    - kind: Rule
      match: Host(`go-intern-api.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 14
      services:
        - name: goyoai-gointern-system
          port: 5000
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`go-intern-api.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-gointern-system
          port: 5000
          scheme: h2c
    # - kind: Rule
    #   match: Host(`go-intern-api.goyoai.com`) && PathPrefix(`/echo`)
    #   # match: PathPrefix(`/`) 
    #   priority: 20
    #   middlewares:
    #     - name: forwarded-headers
    #   services:
    #     - name: echo-server
    #       port: 80
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`stage-api.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 14
      services:
        - name: goyoai-gointern-system
          port: 5000
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`stage-api.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-gointern-system
          port: 5000
          scheme: h2c
      # middlewares:
      #   - name: striptransferencoding
  tls:
    secretName: gointern-backend-system-tls
  # Include TLS configuration if Traefik is handling TLS2
