apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-web-back-portal-https
  namespace: goyoai-web
spec:
  entryPoints:
    - websecure
  routes:
    # - kind: Rule
    #   match: Host(`go-intern-api-portal.goyoai.com`)
    #   # match: PathPrefix(`/`) 
    #   priority: 14
    #   services:
    #     - name: goyoai-web-back-portal
    #       port: 5000
    #   # middlewares:
    #   #   - name: striptransferencoding
    # - kind: Rule
    #   match: Host(`go-intern-api-portal.goyoai.com`) && PathPrefix(`/grpc`)
    #   # match: PathPrefix(`/`) 
    #   priority: 15
    #   services:
    #     - name: goyoai-web-back-portal
    #       port: 5000
    #       scheme: h2c
    - kind: Rule
      match: Host(`go-intern-api-portal.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 14
      services:
        - name: goyoai-gointern-portal
          port: 5000
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`go-intern-api-portal.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-gointern-portal
          port: 5000
          scheme: h2c
      # middlewares:
      #   - name: striptransferencoding
  tls:
    secretName: goyoai-web-back-portal-tls
  # Include TLS configuration if Traefik is handling TLS2
