apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: goyoai-web-front-react-https
  namespace: goyoai-web
spec:
  entryPoints:
    - websecure
  routes:
    # - kind: Rule
    #   match: Host(`go-intern2.goyoai.com`)
    #   # match: PathPrefix(`/`) 
    #   priority: 14
    #   services:
    #     - name: goyoai-web-front-react
    #       port: 5001
    #   # middlewares:
    #   #   - name: striptransferencoding
    # - kind: Rule
    #   match: Host(`go-intern2.goyoai.com`) && PathPrefix(`/grpc`)
    #   # match: PathPrefix(`/`) 
    #   priority: 15
    #   services:
    #     - name: goyoai-web-front-react
    #       port: 5001
    #       scheme: h2c

    # - kind: Rule
    #   match: Host(`go-intern-admin.goyoai.com`)
    #   # match: PathPrefix(`/`) 
    #   priority: 14
    #   services:
    #     - name: goyoai-web-front-admin
    #       port: 5000
    #   # middlewares:
    #   #   - name: striptransferencoding
    # - kind: Rule
    #   match: Host(`go-intern-admin.goyoai.com`) && PathPrefix(`/grpc`)
    #   # match: PathPrefix(`/`) 
    #   priority: 15
    #   services:
    #     - name: goyoai-web-front-admin
    #       port: 5000
    #       scheme: h2c

    - kind: Rule
      match: Host(`go-intern.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 14
      services:
        - name: goyoai-gointern-web
          port: 5000
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`go-intern.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-gointern-web
          port: 5000
          scheme: h2c
    - kind: Rule
      match: Host(`ksure.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 14
      services:
        - name: goyoai-web-front-v2
          port: 5001
      # middlewares:
      #   - name: striptransferencoding
    - kind: Rule
      match: Host(`ksure.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 15
      services:
        - name: goyoai-web-front-v2
          port: 5001
          scheme: h2c
      # middlewares:
      #   - name: striptransferencoding

    - kind: Rule
      match: Host(`www.goyoai.com`) || Host(`goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 12
      middlewares:
        - name: redirect-to-www
      services:
        - name: goyoai-web-page
          port: 5000
    - kind: Rule
      match: Host(`www.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 13
      services:
        - name: goyoai-web-page
          port: 5000
          scheme: h2c
    - kind: Rule
      match: Host(`stage.goyoai.com`)
      # match: PathPrefix(`/`) 
      priority: 12
      services:
        - name: goyoai-gointern-web
          port: 5001
    - kind: Rule
      match: Host(`stage.goyoai.com`) && PathPrefix(`/grpc`)
      # match: PathPrefix(`/`) 
      priority: 13
      services:
        - name: goyoai-gointern-web
          port: 5001
          scheme: h2c

    # - kind: Rule
    #   match: Host(`aify.goyoai.com`)
    #   # match: PathPrefix(`/`) 
    #   priority: 12
    #   services:
    #     - name: aify-frontend
    #       # namespace: goyoai-aify
    #       port: 5001
  tls:
    secretName: goyoai-web-front-tls
  # Include TLS configuration if Traefik is handling TLS2
