gitUrl: "https://github.com/GoyoAi-Service/goyoai-ai-server"
gitRevision: "qa"
container_registry_secretName: "harborcred"
common_alpine_url: "gdharbor.goyoai.com/common/alpine:3.19.1"
common_alpine_git_url: "gdharbor.goyoai.com/common/git:2.43.0"
container_registry_url: "gdharbor.goyoai.com/goyoai-web/goyoai-backend-crawler-dev"
container_registry_cache_url: "gdharbor.goyoai.com/goyoai-web/goyoai-backend-crawler-cache-dev"
kustomize_git_url: "https://github.com/GoyoAi-Service/goyoai-web-manifest"
kustomize_git_branch: "goyoai-backend-crawler"
manifestFileName: "goyoai-backend-crawler-manifest.yaml"
commitMessage: "Update Kubernetes manifest"
project_name: "goyoai-backend-crawler"
slack_webhook_url: "https://hooks.slack.com/services/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"