apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-aify-system
spec:
  template:
    spec:
      serviceAccountName: goyoai-vault-sa
      containers:
        - name: goyoai-aify-system-container
          image: gphb.goyoai.com/goyoai-web/goyoai-aify-system:82b14e7-20251217070601
