apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyoai-gointern-message
  labels:
    app.kubernetes.io/component: goyoai-gointern-message-generator
    app.kubernetes.io/instance: goyoai-gointern-message-generator
    app.kubernetes.io/part-of: goyoai-gointern-message-generator
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: goyoai-gointern-message-app
  template:
    metadata:
      labels:
        app: goyoai-gointern-message-app
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      schedulerName: default-scheduler
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "goyo-svc"
                operator: In
                values:
                - "virtual"
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "tekton-build"
        effect: "NoSchedule"

      containers:
      - name: goyoai-gointern-message-container
        image: 770637673430.dkr.ecr.ap-northeast-2.amazonaws.com/goyoai-dev-web-back-v2:e95e154-20231213084356
        ports:
        - containerPort: 9195
          protocol: TCP
        - containerPort: 9292
          protocol: TCP                
        resources:
          requests:
            cpu: "1000m"
            memory: "5Gi" 
          limits:
            cpu: "1000m"
            memory: "5Gi"
        startupProbe:
          httpGet:
            path: /actuator/health/readiness # Liveness/Readiness와 동일한 경로 사용
            port: 9292
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 30
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 9292
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 9292
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File