apiVersion: v1
kind: Secret
metadata:
  name: ai-api-env
  namespace: goyoai-web
type: Opaque
stringData:
  HUGGINGFACEHUB_API_TOKEN: "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"
  OPENAI_API_KEY: "sk-svcacct-2zj_aqtdxri9rWqPNY8kCiosWbxukAcBRjwR7PBUiQGK-6xvTcgHxLUDOVimmMpLHT3BlbkFJnWSml188Rfv1GxUzvFmOBHqMw5KUmT-KVhDLFf765gfRwwevlUfyDhRFCXGV7RnAA"
  DEBUGMODE: "false"
  VECTORDB_HOST: "goyo-chromadb"
  VECTORDB_PORT: "8000"
  DB_URL: "postgresql+asyncpg://goyoai:phowr*XU+AXoml04l2ro@10.130.239.5:5432/prod_goyoai_web"
  POSTGRES_URL: "postgresql+asyncpg://goyoai:phowr*XU+AXoml04l2ro@10.130.239.5:5432/postgres"
  DB_POOL_SIZE: "100"
  DB_MAX_OVERFLOW: "10"
  REDIS_URL: "redis://goyo-ai-api-redis-master.redis.svc.cluster.local:6379"
  MODEL_SERVER: "http://103.139.119.122:15012"  
  MODEL_API_KEY: "goyo123"
  GOYO_BACKEND_SERVER: "http://goyoai-web-back.goyoai-web.svc.cluster.local:5000"
  BBRICK_BACKEND_SERVER: "http://goyoai-web-back-portal:5000"
  BACKEND_API_KEY: "8b2e0f931f4adb5271217eebbac8ff90"
  BACKEND_SECRET_KEY: "18151921918386a8eb2dd8b78b6c135f0001b171e0efd17959cbdb6235a21238"
  LANGFUSE_SECRET_KEY: "sk-lf-efdf9d79-7c7d-472c-b2c6-478ce4e3ca1a"
  LANGFUSE_PUBLIC_KEY: "pk-lf-8312dd51-77cb-44a6-8f38-ed654adc6012"
  LANGFUSE_HOST: "http://goyo-langfuse:3000"
  AMPLITUDE_API_KEY: "2a0bbedf410332c678fb0d191a3e9dc8"
  NAVER_API_CLIENT_ID: "qyinpf1mDIBQmDmZAeCt"
  NAVER_API_CLIENT_SECRET: "ku6K26oBIH"
  OPENAI_ASSISTANT_ID: "asst_nBpOhNqrzZ5YdzScBj35LxFx"
  AZUREAI_SPEECH_API_KEY: "4KUGuMc54MdHMOBWy6zdotb4W54Qftd6pvtJvFciq6zFZj6XJodfJQQJ99AKACNns7RXJ3w3AAAYACOGwCEt"
  AZUREAI_SPEECH_REGION: "koreacentral"